#!/bin/bash
# by Eric Dumazet

run_netperf() {
    loops=$1
    shift
    for ((i=0; i<loops; i++)); do
        netperf -s 2 $@ | awk '/Min/{
            if (!once) {
                print;
                once=1;
            }
        }
        {
            if (NR == 6)
                save = $NF
            else if (NR==7) {
                if (NF > 0)
                    print $NF
                else
                    print save
            } else if (NR==11) {
                print $0
            }
        }' &
    done
    wait
    return 0
}

run_netperf $@ | awk '{if (NF==7) {print $0; next}} {sum += $1} END
{print sum}'
